# OpenDashboard Configuration
opendashboard:
  # possible values - JiscEntryPointProcessor, DemoEntryPointProcessor
  entrypoint: DemoEntryPointProcessor
  # posssible values - JiscAuthenticator, DemoAuthenticator
  authenticator: DemoAuthenticator
  
spring:
  # Mongo settings
  data:
    mongodb:
      uri: mongodb://localhost/od

  
